# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: FastAPI CI/CD

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    name: "FastAPI Test Suite" 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pylint
        pip check

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}/Store
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Run linter
      run: |
        pylint --fail-under=9 Store/**/*.py || echo "⚠️ Puntuación de pylint es baja, por favor mejore el código para alcanzar una puntuación minima 9/10."

